# Generated by Django 3.0.3 on 2020-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0002_auto_20200527_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='personId',
            field=models.IntegerField(default=0),
        ),
    ]
